remote_theme: pages-themes/minimal@v0.2.0
logo: /assets/images/logo_web.png
plugins:
- jekyll-remote-theme 
title: Aaron G. S.
description: PÃ¡gina WEB personal para alojar contenido como proyectos, trayectoria y publicaciones.  
show_downloads: false
google_analytics: G-MQ8DN75W6K
